# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]
title: Juchan Kim
description: Software Engineer in Los Angeles, CA
paginate: 1
pages_list:       
  ABOUT: '/about'
  TRAVEL: '/travel'
  ARCHIVE: '/archive'
instagram_username: __j_kim_
linkedin_username: juchankim
github_username: juchankim
email_addr: yj1877@berkeley.edu