# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]
title: Juchan Kim
description: Software Engineer in Los Angeles, CA
paginate: 1
pages_list:       
  About: '/about'
  Resume: 'assets/resume.pdf'